export const INCREMENT = 'INCREMENT'

export const GETGOODSLIST = 'GETGOODSLIST'

export const GOODSLISTADD = 'GOODSLISTADD'

export const GOODSLISTSUB = 'GOODSLISTSUB'

export const ADDTOCART = 'ADDTOCART'

export const CARTADD = 'CARTADD'

export const CARTLISTADD = 'CARTLISTADD'

export const CARTLISTSUB = 'CARTLISTSUB'

export const CARTLISTDEL = 'CARTLISTDEL'
